class_name HeroAsset
extends RefCounted
## M2.4 — instantiates a high-fidelity imported GLB (original Meshy-authored
## Japanese rural house) as a reusable, grounded, collidable node. Preserves
## the asset's 2K PBR materials (Godot imports base/normal/metallic-roughness
## from the .glb; LODs are generated by the import step). Never replaces the
## asset with primitives. Writes no environment/lights (M2.2/M2.3 untouched).
##
## Origin fix: Meshy meshes are centred on their own origin, so the base sits
## below y=0. This builder measures the mesh AABB, scales it to a target width,
## lifts it so the base rests exactly on the ground, and builds a SIMPLE box
## collider from the scaled bounds (not the 400k-tri mesh).

## Build a house node from a GLB path. `target_width` is the desired real-world
## width in metres (Meshy exports are ~2 units, so houses scale up). `collide`
## adds a cheap box StaticBody so the player can't walk through it.
static func make_house(glb_path: String, target_width: float = 7.0,
		collide: bool = true) -> Node3D:
	var root := Node3D.new()
	root.name = "House"
	var packed := load(glb_path) as PackedScene
	if packed == null:
		push_error("HeroAsset: could not load '%s'" % glb_path)
		return root
	var inst := packed.instantiate() as Node3D
	var mi := _find_mesh(inst)
	var aabb := mi.get_aabb() if mi != null else AABB(Vector3(-1, -1, -1), Vector3(2, 2, 2))

	var footprint := maxf(aabb.size.x, aabb.size.z)
	var s := target_width / maxf(footprint, 0.001)
	inst.scale = Vector3(s, s, s)
	# Lift so the mesh's lowest point sits at local y = 0 (rests on the ground).
	inst.position = Vector3(-aabb.position.x * s, -aabb.position.y * s, -aabb.position.z * s)
	root.add_child(inst)

	if collide:
		var body := StaticBody3D.new()
		body.name = "Collision"
		var col := CollisionShape3D.new()
		var box := BoxShape3D.new()
		box.size = aabb.size * s
		col.shape = box
		# Box centred on the footprint, half-height above the ground.
		col.position = Vector3(aabb.size.x * s * 0.5, aabb.size.y * s * 0.5, aabb.size.z * s * 0.5)
		body.add_child(col)
		root.add_child(body)
	return root

## The mesh AABB (in raw GLB-local space) and the uniform scale make_house
## applies for a given target width. Lets a caller map REAL measured points on
## the mesh (e.g. the actual doorway/wall lines, read off rendered elevations)
## into the built house's local node space: node = (raw - aabb.position) * scale.
## This is how the hero-house entrance/collision is derived from actual geometry
## rather than guessed from the bounding box.
static func aabb_and_scale(glb_path: String, target_width: float) -> Dictionary:
	var packed := load(glb_path) as PackedScene
	if packed == null:
		return {"aabb": AABB(Vector3(-1, -1, -1), Vector3(2, 2, 2)), "scale": 1.0}
	var inst := packed.instantiate() as Node3D
	var mi := _find_mesh(inst)
	var aabb := mi.get_aabb() if mi != null else AABB(Vector3(-1, -1, -1), Vector3(2, 2, 2))
	var footprint := maxf(aabb.size.x, aabb.size.z)
	var s := target_width / maxf(footprint, 0.001)
	inst.queue_free()
	return {"aabb": aabb, "scale": s}

## The footprint (x/z size in metres) of a built house, for laying out
## vegetation exclusions around it.
static func footprint_of(node: Node3D) -> Vector2:
	var mi := _find_mesh(node)
	if mi == null:
		return Vector2(7.0, 7.0)
	var body := node.get_node_or_null("Collision/CollisionShape3D") as CollisionShape3D
	if body != null and body.shape is BoxShape3D:
		var sz := (body.shape as BoxShape3D).size
		return Vector2(sz.x, sz.z)
	return Vector2(7.0, 7.0)

static func _find_mesh(n: Node) -> MeshInstance3D:
	if n is MeshInstance3D:
		return n
	for c in n.get_children():
		var found := _find_mesh(c)
		if found != null:
			return found
	return null
