#!/usr/bin/env bash
# Create the standard Android *debug* keystore used to sign debug APKs.
# Debug keystores use well-known credentials (password "android") and are
# NOT secret — but we still git-ignore it and regenerate it deterministically
# here so nothing binary is committed. A RELEASE keystore is a different,
# secret thing and must never be committed or generated by CI.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/tools/android/debug.keystore"
mkdir -p "$(dirname "$OUT")"

if [ -f "$OUT" ]; then
	echo "debug keystore already exists: $OUT"
	exit 0
fi

keytool -genkeypair -v \
	-keystore "$OUT" \
	-alias androiddebugkey \
	-keyalg RSA -keysize 2048 -validity 10000 \
	-storepass android -keypass android \
	-dname "CN=Android Debug,O=Android,C=US"

echo "created: $OUT"
echo "  alias=androiddebugkey  storepass=android  keypass=android"
